### ISSUE TITLE
Fix Linux desync issue

### ISSUE THREAD

**Issue by TylerKehne** [TylerKehne/sm64-tas-scripting#51]
311 vs 354 frames on Windows

**Comment by wheatman** [comment]
I did some debugging of this and wasn't able to figure out what it was, one thing I tried was to remove the impact of the clock, I removed all references to `std::chrono::high_resolution_clock::now` and swapped it out for a simple function which returns 1 higher each time 

```
static uint64_t tp=0;
inline std::chrono::time_point<std::chrono::high_resolution_clock> fake_clock()
{
	tp++;
	return std::chrono::time_point<std::chrono::high_resolution_clock>(std::chrono::high_resolution_clock::duration{tp});
}
```
And I still got the same difference across the two versions

**Comment by TylerKehne** [comment]
We found that the desync was caused by a compiler setting on libsm64
